// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImage(arg1, arg2) {
  return window['go']['main']['App']['AddImage'](arg1, arg2);
}

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function GetCandidates() {
  return window['go']['main']['App']['GetCandidates']();
}

export function GetCurrentRound() {
  return window['go']['main']['App']['GetCurrentRound']();
}

export function GetFinalWinner() {
  return window['go']['main']['App']['GetFinalWinner']();
}

export function GetImageList(arg1, arg2) {
  return window['go']['main']['App']['GetImageList'](arg1, arg2);
}

export function GetImageNum() {
  return window['go']['main']['App']['GetImageNum']();
}

export function GetTotalRound() {
  return window['go']['main']['App']['GetTotalRound']();
}

export function GoToNextRound() {
  return window['go']['main']['App']['GoToNextRound']();
}

export function SelectWinner(arg1, arg2) {
  return window['go']['main']['App']['SelectWinner'](arg1, arg2);
}

export function StartTournament() {
  return window['go']['main']['App']['StartTournament']();
}
