// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {images} from '../models';

export function AddImage(arg1:string,arg2:string):Promise<string>;

export function DeleteImage(arg1:string):Promise<void>;

export function GetCandidates():Promise<Array<images.Image>>;

export function GetCurrentRound():Promise<number>;

export function GetFinalWinner():Promise<images.Image>;

export function GetImageList(arg1:number,arg2:number):Promise<Array<images.Image>>;

export function GetImageNum():Promise<number>;

export function GetTotalRound():Promise<number>;

export function GoToNextRound():Promise<boolean>;

export function SelectWinner(arg1:string,arg2:string):Promise<void>;

export function StartTournament():Promise<void>;
